Задание 6-го спринта
klv2503/java-kanban pull request #1
Opened 2024-06-22 07:14 UTC by klv2503

1. Сделать новую версию хранения истории.
Реализовано в классе InMemoryHistoryManager. Код в истории это символьная строка <признак класса - буква t, s или e> + <номер объекта данного класса>. Это выглядит лучше, чем введение сплошной нумерации для всех объектов классов Task, SubTask и Epic. Правки в классе HistoryManager адаптируют его под новую версию. 
2. Реализовать операции с HashMap, хранящей историю
Также реализовано в классе InMemoryHistoryManager. Требование удалять из истории удаленные Task, SubTask и Epic реализовано путем доработки некольких методов в InMemoryTaskManager.
Чтобы иметь возможность удалять подзадачи эпика из истории (потребовалось различать экземпляр из существующего эпика и экземпляр из удаленного) добавлено новое поле в SubTask. Теперь считается, что 
а) все экземпляры SubTask различаются по этому полю
б) каждый экземпляр существует только для одного фиксированного эпика
Изменения затронули сам класс SubTask, несколько методов класса Epic, и связанные с обработкой SubTask методы InMemoryTaskManager.
4. Адаптировать к изменениям тесты
Тесты, написанные ранее, адаптированы к перечисленным изменениям. Добавлены тесты для проверки функционирования (хранение, добавление, удаление элементов) HashMap истории.

2024-06-22 20:52 UTC, db-exp requested changes

2024-06-22 20:52 UTC, db-exp commented on src/ru/taskmanagment/InMemoryHistoryManager.java
> +    static class Node<E> {
лучше все таки вынести в отдельный файл

2024-06-25 10:17 UTC, klv2503 commented on src/ru/taskmanagment/InMemoryHistoryManager.java
> +    static class Node<E> {
Класс Node вынес в отдельный файл. При контрольном запуске проявилась ошибка в методе в InMemoryTaskManager (ранее то ли не проявлялась, то ли не замечал). Переменную переименовал, чтобы было ясно, что не индекс передается, а именно номер задачи во внутренней нумерации эпика.

2024-06-25 20:16 UTC, db-exp approved these changes

2024-06-26 18:41 UTC, merged