Выполнение ТЗ к Спринту 9.
klv2503/java-kanban pull request #13
Opened 2024-08-12 09:15 UTC by klv2503

У себя тестировал в Insomnia. Добился, чтобы работали. Тесты на HttpTaskServer набросал, возможно не все, но основные вроде есть. Часть из из ранее написанных методов явно себя изжила, какие-то из них переписаны под новые потребности. Полную ревизию провести не успел.

2024-08-12 16:24 UTC, db-exp requested changes

2024-08-12 16:24 UTC, db-exp commented on src/ru/httpworks/BaseHttpHandler.java
> +        h.getResponseHeaders().add("Content-Type", "application/json;charset=utf-8");
давай заголовок в константу?

2024-08-12 16:24 UTC, db-exp commented on src/ru/httpworks/EpicsHttpHandler.java
> +    TaskManager manager;
private

2024-08-12 16:24 UTC, db-exp commented on src/ru/httpworks/EpicsHttpHandler.java
> +    TaskManager manager;
+ final

2024-08-12 16:24 UTC, db-exp commented on src/ru/httpworks/HistoryHttpHandler.java
> +    TaskManager manager;
private final

2024-08-13 10:23 UTC, klv2503 commented on src/ru/httpworks/BaseHttpHandler.java
> +        h.getResponseHeaders().add("Content-Type", "application/json;charset=utf-8");
Если я правильно понял, этот вопрос является не столько указанием завести константу, сколько намёком на то, что методы класса по сути идентичны. Поэтому собрал всех в один. Странно, что я на это сам не обратил внимания. Скорее всего, мысли были заняты алгоритмами сервера, а технические детали (типа реализация ответа по данному в ТЗ шаблону) в подсознании считались решенными. А вот комментарий по поводу сохранения файлов .idea, честно говоря, не понял. Прошу пояснить

2024-08-13 10:25 UTC, klv2503 commented on src/ru/httpworks/EpicsHttpHandler.java
> +    TaskManager manager;
Добавил у всех пяти обработчиков.

2024-08-13 13:35 UTC, db-exp approved these changes

2024-08-14 11:28 UTC, merged