Задание 7-го спринта
klv2503/java-kanban pull request #3
Opened 2024-07-07 06:00 UTC by klv2503

Добавлены классы FileBackedTaskManager и ManagerSaveException для работы с файлами и класс для тестирования нового менеджера. Также добавлен класс TaskTypes. В классе InMemoryTaskManager уточнена работа некольких методов. Остальные классы подправлены с учетом указанных изменений.

2024-07-08 09:58 UTC, db-exp requested changes

2024-07-08 09:58 UTC, db-exp commented on src/ru/taskmanagment/FileBackedTaskManager.java
> +    public String toString(Task task) {
такое лучше у каждого типа отдельно сделать переопределением стандартного toString

2024-07-08 09:58 UTC, db-exp commented on src/ru/taskmanagment/FileBackedTaskManager.java
> +        //Теперь предполагается, что файл пишется один раз в конце работы программы.
более правильно сохранять каждый раз при изменении задачи, потому что при внезапном прерывании программы состояние потеряется

2024-07-08 09:58 UTC, db-exp commented on src/ru/taskmanagment/FileBackedTaskManager.java
> +            bufferedWriter.close();
тут можно пользоваться try with resource и не закрывать явно

2024-07-08 14:27 UTC, klv2503 commented on src/ru/taskmanagment/FileBackedTaskManager.java
> +    public String toString(Task task) {
Здесь есть вопрос. Название метода в FileBackedTaskManager взято согласно ТЗ к спринту. Для Task, SubTask и Epic ещё с первой версии toString'и  переопределены для наглядности вывода в консоль, но для записи в файл они не подходят.  Их заменить не проблема, но тогда вывод в консоль станет выглядеть соответсвенно. Может, просто "здешний" метод переименовать, чтобы не было разночтений? Скажем, в convertDataToString?

2024-07-09 09:46 UTC, db-exp approved these changes

2024-07-10 05:28 UTC, merged